postgres_practice:
  target: dev
  outputs:
    dev:
      type: postgres
      host: [hostname]
      user: matt
      password: password
      port: 5432
      dbname: practice
      schema: test
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 500 # default 10 seconds